[build]
  command = "gatsby build && npm run generate-cv"
  publish = "public/"

[template]
  incoming-hooks = ["Ghost"]

[[headers]]
  for = "/*"
  [headers.values]
	  cache-control = '''
	  max-age=0,
	  no-cache,
	  no-store,
	  must-revalidate'''
